-- Create shared_links table
CREATE TABLE IF NOT EXISTS public.shared_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  name TEXT NOT NULL,
  project_url TEXT NOT NULL,
  description TEXT
);

-- Add RLS policies
ALTER TABLE public.shared_links ENABLE ROW LEVEL SECURITY;

-- Allow anonymous reads
CREATE POLICY "Allow anonymous read access to shared_links" 
  ON public.shared_links
  FOR SELECT
  USING (true);

-- Allow anonymous inserts
CREATE POLICY "Allow anonymous insert access to shared_links" 
  ON public.shared_links
  FOR INSERT
  WITH CHECK (true);

-- Add appropriate indexes
CREATE INDEX IF NOT EXISTS shared_links_created_at_idx ON public.shared_links (created_at DESC); 